### ISSUE TITLE
PyNN on NEST docker

### ISSUE THREAD

**Issue by pabogdan** [steffengraber/nest-docker#2]
Thank you very much for making docker containers for NEST. However, as far as I can tell these containers don't have support for PyNN. Would it be possible to add PyNN to at least one of them?

**Comment by steffengraber** [comment]
Thanks for the tip. I'll integrate it over the next few days.

**Comment by pabogdan** [comment]
I've managed to do it in a private container following a tip of yours I found on some forum. It would still probably be extremely useful for people wanting to use nest if they could instantly use yours.

**Comment by steffengraber** [comment]
Hi @pabogdan no matter how I install PyNN, I see the message "Unable to install NEST extensions. Certain models may not be available.".
Did you solve that?

I installed PyNN from the` nest-dev` branch and, as mentioned in the documentation, I also tried `pip install --no-binary :all: PyNN`.
 nest-config is in the PATH.

**Comment by pabogdan** [comment]
I have just re-built that docker container and saved the stdout output in a log file. Searching for "Unable to install NEST extensions" yielded no results. 

The (most) relevant bits of my installation are:

```
RUN git clone https://github.com/nest/nest-simulator.git
RUN cmake -DCMAKE_INSTALL_PREFIX:PATH=/nest_dev /nest_dev/nest-simulator -DPYTHON_EXECUTABLE=/usr/local/bin/python
RUN make && make install && make installcheck
# From https://www.nest-simulator.org/mailinglist/hyperkitty/list/users@nest-simulator.org/thread/VAZMC73JMOFUD7YZVFHYBMM5CXE7CZYK/
RUN wget https://github.com/NeuralEnsemble/PyNN/archive/nest-dev.tar.gz
RUN tar -xzf nest-dev.tar.gz
RUN /bin/bash -c "cd PyNN-nest-dev && python3 setup.py install && cd -"
```

I also do not recall seeing this error while running simulations.

**Comment by steffengraber** [comment]
Okay, thanks a lot. That looks like what I did. 
The message appears when I test pyNN with:

`>>> import pyNN.nest as sim`

**Comment by steffengraber** [comment]
The documentation - http://neuralensemble.org/docs/PyNN/installation.html - says:

Warning

If you get a warning “Unable to install NEST extensions. Certain models may not be available” then ensure the program nest-config is on your system PATH. If you still get this message even after adding the directory containing nest-config to the PATH, try pip uninstall PyNN, then re-install with pip install --no-binary :all: PyNN 

But that doesn't help either.

**Comment by pabogdan** [comment]
I've just checked a model I ran. I get the same warning but the model runs successfully. What falls under "NEST extensions"? Topology / structural plasticity?

@apdavison any thoughts?

**Comment by apdavison** [comment]
PyNN provides a couple of extra, optional models as NEST extensions. The extensions are supposed to be built during `setup.py install`. I can look into this after the HBP Summit.

By the way, are you aware of https://github.com/neuralEnsemble/neuralensemble-docker/ ? These images provide PyNN, NEST, and some other simulators (although I note we need to update to NEST 2.18.0)

**Comment by pabogdan** [comment]
I was not aware of these containers. This is awesome! 

I also think I understand why I did not know about it. The search functionality on docker hub did not pick up https://hub.docker.com/r/neuralensemble/simulation

Thank you for bringing this to my attention!

**Comment by steffengraber** [comment]
I took a closer look at the neuroensemble docker and installed NEST 2.18.0 in it. To do this, I added neurodebian:bionic to the base docker file and added NEST 2.18.0 to the simulation docker file.  Unfortunately I did not get the  libneurosim to work, so it was disabled. I installed PyNN like this: 
`RUN pip install --no-binary :all: PyNN`

Then I made a build of the Docker images, which worked. A:
`import pyNN.nest as sim`
led to the expected error messages because of the missing libneurosim but also again to the message:

> ...pyNN/nest/__init__.py:53: UserWarning:Unable to install NEST extensions Certain models may not be available.

@apdavison Would be really great if you could take a look at this.

**Comment by steffengraber** [comment]
Closed due to inactivity.
